### ISSUE TITLE
version 3.1 of the newrelic_rpm gem breaks padrino-rpm

### ISSUE THREAD

**Issue by Xylakant** [Asquera/padrino-rpm#1]
Error message is

```
no such file to load -- new_relic/rack_app
/home/vagrant/.rvm/gems/ruby-1.9.2-p180/bundler/gems/padrino-rpm-f80757306851/lib/padrino-rpm.rb:37:in `require'
/home/vagrant/.rvm/gems/ruby-1.9.2-p180/bundler/gems/padrino-rpm-f80757306851/lib/padrino-rpm.rb:37:in `block in <top (required)>'
```

**Comment by keo** [comment]
fixed here: https://github.com/Asquera/padrino-rpm/pull/3
